### PR TITLE
Capture filtering

### LINKED ISSUE #33: Capture filter
We need one of these for quiescence, or otherwise a dedicated capture generator. Since the latter gives us little, I think filtering is fine.

### PR DESCRIPTION
**Pull request by Ravenslofty**
Resolves #33.

### CODE REVIEW

**Comment by japanoise** [comment]
Resolves? No. But it's good utility code for when we want to get this feature implemented.

**Comment by japanoise** [comment]
So a couple of things:

1. Let's get this covered by unit tests as discussed over IRC
2. Fix indentation (tabs, as per `go fmt`)

**Comment by japanoise** [comment]
Further to the discussion on IRC, I think we can see this actually does resolve the issue - will close #35

**Comment by ZirconiumX** [comment]
Yes ma'am. o7

**Pull request merged**
